
{

   # topics of interest
  "topics": {
    "image" : "/dvs/image_raw",
    "tf"  : "/tf",
    "event" : "/dvs/events"
    },

  "camera": {

    "fx" : 298.67179975,
    "fy" : 298.59720232,
    "cx" : 176.38660484,
    "cy" : 119.96968706,

    "k1" : -0.37074772,
    "k2" : 0.14798075,
    "k3" : 0.0,
    "p1" : 0.00251884,
    "p2" : -0.00170605,

    "image_width" : 346,
    "image_height" : 260
  },

  "pattern" : [10,7],

  "event_buffer_time_ns" : 500000000,

  "feature_toggle" : {'hough' : 1,
                      'circlesGrid' : 0}
}
